app/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('login',  array('as' => 'login.index', 'uses' => 'AuthController@index'));

Route::post('login', array('as' => 'login.signin', 'uses' => 'AuthController@sign_in'));

//Route::group(array('before' => 'auth'), function () {

	Route::get('/', array('as' => 'home.index', 'uses' => 'HomeController@index'));

	Route::get('perfil', array('as' => 'perfil', 'uses' => 'UsersController@perfil'));

	Route::get('logout', array('as' => 'login.logout', 'uses' => 'AuthController@sign_out'));

	Route::resource('users', 'UsersController');

	Route::resource('molds', 'MoldsController');

	Route::resource('lines', 'LinesController');

	Route::resource('efficiency', 'EfficiencyController');

	Route::resource('devices', 'DevicesController');

	Route::resource('production', 'ProductionController');

	Route::get('production/history/{line_id}/{model_id?}/{start_date?}/{end_date?}',
		array(
			'as' => 'production_history',
			'uses' => 'ProductionController@history')
		);

	Route::resource('defects', 'DefectsController');

	Route::resource('models', 'ModelsController');

	Route::resource('plan', 'PlanController');

	Route::get('plan_mold/{mold_id}', 'PlanController@plan_mold');

//});

/*Route::filter('auth', function()
{
    if (Auth::guest()) return Redirect::to('login');
});*/

Route::get('register_production', 'ProductionController@register_production');

$path =  Request::segment(1);

Session::put('nav-option', $path);

//no mismo plan en el mismo horario dependiendo de la linea

//localhost:8000/register_production?line_id=1&arduino_id=1

app/models/Defect.php
<?php
	class Defect extends Eloquent {
		/*public function production(){
			return $this->hasMany('Production', 'arduino_id');
		}*/

		protected $table = 'defects';

		public static $rules = array(
	      'name' => 'required|min:2',
	      'def_description' => 'required|min:2',
	   );

		public static $messages = array( /////////////////////////Edit/////////////////////////////////
	      	'name.required' => 'Requerido',
	      	'def_description.required' => 'Requerido'
	   	);

	   	public function problemproduction (){
			return $this->belongsTo('problemproduction');
		}

		public static function validate($data, $id=null){
	      $reglas = self::$rules;
	      $messages = self::$messages;
	      return Validator::make($data, $reglas, $messages);
	   }
	}
?>

app/models/DefectiveProduction.php
<?php
	class DefectiveProduction extends Eloquent {

		public function line() {
			return $this->belongsTo('Line');
		}
		public function user() {
			return $this->belongsTo('User');
		}
		public function model() {
			return $this->belongsTo('Model');
		}
		public function defect() {
			return $this->belongsTo('Defect');
		}

		protected $table = 'defective_production';
	}
?>

app/models/Device.php
<?php
	class Device extends Eloquent {
		/*public function production(){
			return $this->hasMany('Production', 'arduino_id');
		}*/

		protected $table = 'devices';
	}
?>

app/models/Discussion.php
<?php
	class Discussion extends Eloquent {

		protected $table = 'discussion';
	}
?>

app/models/Efficiency.php
<?php
	class Efficiency extends Eloquent {
		
		protected $table = 'efficiency';

		public function line() {
			return $this->belongsTo('Line');
		}
		public function Shift() {
			return $this->belongsTo('Shift');
		}
		public function model() {
			return $this->belongsTo('Model');
		}

		

		/*public static $rules = array(
	      'lin_description' => 'required|min:2'
	   );

		public static $messages = array( /////////////////////////Edit/////////////////////////////////
	      	'lin_description.required' => 'Requerido.'
	   	);
		public static function validate($data, $id=null){
	      $reglas = self::$rules;
	      $messages = self::$messages;
	      return Validator::make($data, $reglas, $messages);
	   }*/

	}
?>

app/models/EfficiencyDefects.php
<?php
	class EfficiencyDefects extends Eloquent {

		public function defect() {
			return $this->belongsTo('Defect');
		}

		protected $table = 'efficiency_defects';
	}
?>

app/models/Line.php
<?php
	class Line extends Eloquent {
		
		/*public function production(){
			return $this->belongsTo('Production');
		}*/
		public function modelos() {
			//return $this->belongsToMany('Model', 'productions', 'line_id', 'model_id');
		}

		public function plans() {
			return $this->hasMany('Plan');
		}

		public function device () {
			return $this->belongsTo('Device', 'device_id', 'id');
		}
		protected $table = 'lines';

	}
?>

app/models/Model.php
<?php
	class Model extends Eloquent {

		public function mold() {
			return $this->belongsTo('Mold', 'mold_id', 'id');
		}

		protected $table = 'models';

	}
?>

app/models/Mold.php
<?php
class Mold extends Eloquent{

	public function models() {
		return $this->hasMany('Model');
	}

	protected $table = 'molds';

	public static $rules = array(
      'codigo' => 'required|min:2',
      'mol_description' => 'required'
   );
	
}
?>

app/models/Plan.php
<?php
	class Plan extends Eloquent {
		/*public function production(){
			return $this->belongsTo('Production');
		}*/
		public function line() {
			return $this->belongsTo('Line');
		}
		public function user() {
			return $this->belongsTo('User');
		}
		public function model() {
			return $this->belongsTo('Model');
		}
		
		public function shift() {
			return $this->belongsTo('Shift');
		}

		public function type () {
			return $this->belongsTo('PlanType', 'type_id', 'id');
		}

		protected $table = 'plan';
	}
?>

app/models/PlanType.php
<?php
	class PlanType extends Eloquent {

		protected $table = 'plan_type';
	}
?>

app/models/Post.php
<?php
	class Post extends Eloquent {
		public function user(){
			return $this->belongsTo('User');
		}
		protected $table = 'posts';
	}
?>

app/models/ProblemProduction.php
<?php
	class ProblemProduction extends Eloquent {
		
		public static $rules = array(
			'name' => 'required',
	      'pp_description' => 'required|min:2',
	   );

		public static $messages = array( /////////////////////////Edit/////////////////////////////////
			'name' => 'Requerido',
	      	'pp_description.required' => 'Requerido'
	   	);

		public static function validate($data, $id=null){
	      $reglas = self::$rules;
	      $messages = self::$messages;
	      return Validator::make($data, $reglas, $messages);
	   }

		protected $table = 'problem_production';

	}
?>

app/models/Production.php
<?php
	class Production extends Eloquent {

		public function line() {
			return $this->belongsTo('Line', 'line_id', 'id');
		}

		public function user() {
			return $this->belongsTo('User');
		}

		public function plan () {
			return $this->belongsTo('Plan', 'plan_id', 'id');
		}

		public function model () {
			return $this->belongsTo('Model', 'model_id', 'id');
		}

		protected $table = 'productions';

		public function get_total () {

			
			
		}
	}
?>

app/models/Shift.php
<?php
	class Shift extends Eloquent {
		/*public function user(){
			return $this->belongsTo('User');
		}*/
		protected $table = 'shifts';

		public static $rules = array(
	      'shi_description' => 'required|min:2',
	   );

		public static $messages = array( /////////////////////////Edit/////////////////////////////////
	      	'shi_description.required' => 'Requerido'
	   	);
	   	
		public static function validate($data, $id=null){
	      $reglas = self::$rules;
	      $messages = self::$messages;
	      return Validator::make($data, $reglas, $messages);
	   }
		
	}
?>

app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the token value for the "remember me" session.
	 *
	 * @return string
	 */
	public function getRememberToken()
	{
		return $this->remember_token;
	}

	public function type() {
		return $this->belongsTo('UserType', 'usertype_id', 'id');
	}


	/**
	 * Set the token value for the "remember me" session.
	 *
	 * @param  string  $value
	 * @return void
	 */
	public function setRememberToken($value)
	{
		$this->remember_token = $value;
	}

	/**
	 * Get the column name for the "remember me" token.
	 *
	 * @return string
	 */
	public function getRememberTokenName()
	{
		return 'remember_token';
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}

	/**
	 * Hash password
	 *
	 * @param string
	 */
	public function setPasswordAttribute($password)
	{
		$this->attributes['password'] = Hash::make($password);
	}

	/**
	 * Fillable attributes
	 *
	 * @var array
	 */
	protected $fillable = array('name', 'password', 'name', 'email', 'active', 'usertype_id', 'created_at');

	/**
	 * Create rules
	 *
	 * @var array
	 */
	/*public static $createRules = array(
		'username' => 'required',
		'name'     => 'required'
	);
*/
	/**
	 * Update rules
	 *
	 * @var array
	 */
	/*public static $updateRules = array(
		'email' => 'required',
		'password' => 'required_with:change-password|min:6',
		'name'     => 'required'
	);*/

}

app/models/UserType.php
<?php
	class UserType extends Eloquent {

		protected $table = 'user_type';
	}
?>

app/controllers/ModelsController.php
<?php
class ModelsController extends BaseController {

   private $autorizado;

   public function __construct() {

   }
   
   public function index() {

      if (Input::get('search')) {

         $search = Input::get('search');

         $models = Model::where('name', 'LIKE', '%'. $search .'%')->orWhere('description', 'LIKE', '%'. $search. '%')->paginate(12);

         $models->appends(Input::only('search'));

      } else {

         $models = Model::paginate(12);

      }

      return View::make('models.index', compact('models'));
   }

   public function show($id) {

      $model = Model::find($id);

      return View::make('models.show', compact('model'));
   }

   public function create() {

      $model = new Model();
      $molds = Mold::lists('name', 'id');
      return View::make('models.save', compact('molds', 'model'));
   }

   public function store() {

      try {

         $model = new Model();

         $model->name = Input::get('name');

         $model->description = Input::get('description');

         $model->cavity = Input::get('cavity');

         $model->mold_id = Input::get('mold_id');

         $model->save();
         
      } catch (Exception $e) {
         
         return Redirect::back();
      }

      return Redirect::to('models')->with('notice', 'El modelo ha sido creado correctamente');
   }
   public function edit($id) {

      $model = Model::find($id);
      
      $molds = Mold::lists('name', 'id');
      
      return View::make('models.edit', compact('model', 'molds'));
   }

   public function update($id) {

      try {

         $model = Model::find($id);

         $model->name = Input::get('name');
         $model->description = Input::get('description');
         $model->mold_id = Input::get('mold_id');
         $model->cavity = Input::get('cavity');
         $model->save();
         
      } catch (Exception $e) {
         
         return Redirect::back();
      }
      return Redirect::to('models')->with('notice', 'El modelo ha sido modificado correctamente');
   }
   public function destroy($id) {

      try {
         
         $model = Model::find($id);

         $model->delete();
         
      } catch (Exception $e) {
         
         return Redirect::back();
      }

      return Redirect::back()->with('notice', 'Registro eliminado');
   }
}
?>

app/views/models/_form.blade.php
<div class="form-group">
  {{ Form::label ('name', 'Nombre') }}
	  {{ Form::text ('name', null, array('class' => 'form-control')) }}
</div>
<div class="form-group">
  {{ Form::label ('description', 'Descripción') }}
  {{ Form::textarea ('description',null, array('class' => 'form-control')) }}
</div>
<div class="form-group">
  {{ Form::label ('cavity', 'Cavidad') }}
	  {{ Form::text ('cavity', null, array('class' => 'form-control')) }}
</div>
<div class="form-group">
  {{ Form::label ('mold_id', 'Molde') }}
  {{ Form::select('mold_id', array('0'=> '-- Selecciona --') + $molds, array('selected' => $model->mold_id), array('class' => 'form-control'))}}
</div>

<div class="form-group">
    {{ Form::submit('Guardar', array('class' => 'btn btn-success')) }}
	{{ link_to('models', 'Canceler', null, array('class' => 'text-danger')) }}
</div>

app/views/models/edit.blade.php
@extends('layouts.master')
@section('content')
  
  @if(isset($errors))
	   <ul>
	      @foreach($errors as $item)
	         <li> {{ $item }} </li>
	      @endforeach
	   </ul>
	@endif

 <div>
  {{ Form::model($model, array('method' => 'PUT' ,'route' => array('models.update', $model->id), 'id' => '')) }}
    @include('models._form')
  {{ Form::close() }}
  </div>
@stop

app/views/models/index.blade.php
@extends('layouts.master')
@section('content')

@if(Session::has('notice'))
    <div class="alert alert-success">  {{  Session::get('notice') }}
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    </div>
@endif
<div class="row">
    <div class="col-md-6">
        <h3 class="pull-left">Modelos
            {{ link_to_route('models.create', ' Nuevo', null, array('class' => 'btn btn-success')) }} 
        
        </h3>
    </div>
</div>
<div>
    <table class="table">
        <thead>
            <tr>
                <th> Modelo </th>
                <th> Descrición </th>
                <th> Modelo</th>
                <th> Cavidad</th>
                <th colspan="2"> Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($models as $model)
            <tr class="">
                <td>{{ $model->name }}</td>
                <td> {{ ($model->description) ? $model->description : 'Sin descripción' }} </td>
                <td>
                @if($model->mold)
                    {{ $model->mold->name }}
                @else
                    <i class="text-danger">Molde no asignado</i>
                @endif
                </td>
                <td>
                    @if($model->cavity)
                        {{ $model->cavity }}
                    @else
                        <i class="text-danger">No asignado</i>
                    @endif
                </td>
                <td> 
                    {{ link_to_route('models.edit', 'Editar', $model->id, array('class' => 'btn btn-primary')) }}
                </td>
                <td>
                    {{ Form::open(array('method' => 'DELETE', 'route' => array('models.destroy', $model->id))) }}
                        {{ Form::submit('Eliminiar', array('class' => 'btn btn-danger destroy-register'))}}
                    {{ Form::close() }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@if($models->count())
     {{ $models->links() }}
@else
    <p class="text-danger">No se encontro registros</p>
@endif
@stop

app/views/models/save.blade.php
@extends('layouts.master')
@section('content')

  @if(isset($errors))
	   <ul>
	      @foreach($errors as $item)
	         <li> {{ $item }} </li>
	      @endforeach
	   </ul>
	@endif
 <div class="content-data" id="">
  {{ Form::open(array('url' => 'models/' . $model->id)) }}
    @include('models._form')
  {{ Form::close() }}
</div>
@stop

app/views/models/show.blade.php
@extends('layouts.master')
@section('content')
	@if($model)
    	<h1> Modelo {{ $model->id }} </h1>
    
       	<span>Nombre: {{ $model->name }} </span><br />
       	@if($model->mold)
       		<span>Nombre de molde: {{ $model->mold->name }} </span>
    	@endif

    	<p> {{ link_to_route('models.edit', 'Editar', $model->id, array('class' => 'btn btn-primary')) }} 
    	{{ link_to('models', 'Volver atrás') }} </p>
    @endif
@stop