app/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('login',  array('as' => 'login.index', 'uses' => 'AuthController@index'));

Route::post('login', array('as' => 'login.signin', 'uses' => 'AuthController@sign_in'));

//Route::group(array('before' => 'auth'), function () {

	Route::get('/', array('as' => 'home.index', 'uses' => 'HomeController@index'));

	Route::get('perfil', array('as' => 'perfil', 'uses' => 'UsersController@perfil'));

	Route::get('logout', array('as' => 'login.logout', 'uses' => 'AuthController@sign_out'));

	Route::resource('users', 'UsersController');

	Route::resource('molds', 'MoldsController');

	Route::resource('lines', 'LinesController');

	Route::resource('efficiency', 'EfficiencyController');

	Route::resource('devices', 'DevicesController');

	Route::resource('production', 'ProductionController');

	Route::get('production/history/{line_id}/{model_id?}/{start_date?}/{end_date?}',
		array(
			'as' => 'production_history',
			'uses' => 'ProductionController@history')
		);

	Route::resource('defects', 'DefectsController');

	Route::resource('models', 'ModelsController');

	Route::resource('plan', 'PlanController');

	Route::get('plan_mold/{mold_id}', 'PlanController@plan_mold');

//});

/*Route::filter('auth', function()
{
    if (Auth::guest()) return Redirect::to('login');
});*/

Route::get('register_production', 'ProductionController@register_production');

$path =  Request::segment(1);

Session::put('nav-option', $path);

//no mismo plan en el mismo horario dependiendo de la linea

//localhost:8000/register_production?line_id=1&arduino_id=1

app/controllers/HomeController.php
<?php

class HomeController extends BaseController {

	public function index()
	{

        $lines = Line::all();

        $productions = Production::select('*', 
                DB::raw('count(line_id) as quantity, line_id as line_name, MIN(created_at) as start_date, MAX(created_at) as end_date ')) //, MAX(created_at) as last_row
                ->groupBy('line_id', 'model_id', 'plan_id')
                ->where(DB::raw('date(created_at)'), date('Y-m-d'))
                ->take(3)
                ->where('plan_id', '>', 0)
                ->get();
            
            return View::make('home.index', compact('productions', 'lines'));
		
	}

    public function register_production() {

        /*try {

            $production = new Production;

            $line_id = Input::get('line_id');


            $plan = Plan::where('line_id', $line_id)
                    ->where('production_date_begin', '<=', date('Y-m-d'))
                    ->where('production_date_end',   '>=', date('Y-m-d'))
                    ->where('production_time_begin', '<=', date('H:i:s'))
                    ->where('production_time_end',   '>=', date('H:i:s'))
                    ->first();

            if (isset($plan->line_id)) {

                $production->plan_id = $plan->id;

            } else {

                $production->plan_id = 0;
            }

            $production->line_id = $line_id;

            $production->arduino_id = Input::get('arduino_id');

            $production->save();
            
        } catch (Exception $e) {
            
            return 'Error al registrar!'.$e;
        }

        return 'Registro agregado!';*/
    }

}

app/views/home/index.blade.php
@extends('layouts.master')
@section('content')

<div class="row">
	<div class="col-md-9">
		<h3>Producción del día de hoy</h3>
	</div>
</div>

<table class="table production-table">
    <thead>
        <th>
            Modelo
        </th>
        <th>
            Linea
        </th>
        <th>
            Plan
        </th>
        <th>
            Total del plan
        </th>
        <th width="180">
            Completo la producción
        </th>
        <th width="200">
            Total por cavidad / Inyecciones
        </th>
    </thead>
    <tbody>
        @foreach($productions as $production)
        <tr href="{{ route('production_history', 
            array(
                ($production->line) ? $production->line->id : $production->line_name, 
                $production->model_id,
                date('Y-m-d', strtotime($production->start_date) ),  
                date('Y-m-d', strtotime($production->end_date) ) ),
                null) }}">
            <td>
                @if($production->plan)
                    @if($production->plan->model)
                        <a href="{{ route('models.show', $production->plan->model->id) }}">
                            {{ $production->plan->model->name }}
                        </a>
                    @else
                        <i class="text-danger">Sin registro</i>
                    @endif
                @else
                    <i class="text-danger">Sin registro</i>
                @endif
            </td>
            <td><!-- LINEA -->
                @if($production->line)
                    <a href="{{ route('lines.show', $production->line->id) }}">{{ $production->line->name }}</a>
                @else
                    <i class="text-danger">Sin registro ({{ $production->line_id }})</i>
                @endif
            </td>
            <td> <!-- ID DE PLAN --> 
                @if($production->plan)
                    <a href="{{ route('plan.show', $production->plan->id) }}" class="label label-primary" style="font-size:14px;">{{ $production->plan->id }}</a>
                @else
                    <i class="text-danger">Sin registro</i>
                    @if($production->plan_id != 0)
                        <p>
                            <b>Plan antiguo</b> ({{ $production->plan_id }})
                        <p>
                    @endif
                @endif
            </td>
            <td>
                @if($production->plan)
                    <b class="label label-info" style="font-size:16px;">{{ $production->plan->quantity }}</b>
                @else
                    <i class="text-danger">Sin registro</i>
                @endif
            </td>
            <td>
                @if($production->plan)
                    <i class="glyphicon {{ finished_production($production, $production->quantity) }}"></i>
                @else
                    <i class="text-danger">Sin registro</i>
                @endif
            </td>

            <td>
                <div>
                    @if($production->model)
                        <span class="label label-success" style="font-size:16px;">
                            {{ get_total_production($production) }}
                        </span>
                    @else
                        0
                    @endif &nbsp; / &nbsp;
                    <span class="label label-warning" style="font-size:16px;">{{ $production->quantity }}</span>
                </div>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@if(!$productions->count())
    <i>No se encontraron registros</i>
@endif

<?php

    $today = date('Y-m-d');

    $dates = array();

    $view_date = array();

    for ($i=0; $i <= 6 ; $i++) {

        $date = strtotime('+'.$i.' day', strtotime($today));

        $dates[$i] = date('Y-m-d', $date);

        $view_date[$i] = date('d D, M', $date);
    }

    $plan_model = Plan::where('production_date_begin', $today)->distinct()->get();
  ?>
<hr />

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th colspan="8">Días</th>
        </tr>
        <tr>
             <th>Modelo</th>
             <th>Linea</th>
            @for($i = 0; $i < sizeof($view_date); $i++)
                <th style="background-color:#CCCCCC;">
                    {{ $view_date[$i] }}
                </th>
            @endfor
        </tr>
    </thead>
    <tbody>
        @foreach($lines as $line)
            <tr>
                <?php
                    $plans = Plan::where('line_id', $line->id)->where('production_date_begin', '>=', $today)
                    ->where('production_date_begin', '<=', $dates[6])
                    ->orderBy('production_time_begin', 'ASC')
                    ->orderBy('production_date_begin', 'ASC')
                    ->get();
                ?>
                @foreach($plans as $plan)
                    <tr>

                        @if($plan->model)
                        <td>
                            <a target="_blank" href="{{ route('plan.show', $plan->id) }}">
                            {{ $plan->model->name }}
                            </a>
                        </td>
                        <td>
                            <a target="_blank" href="{{ route('lines.show', $line->id) }}"> 
                                {{ $line->name }}
                            </a>
                        </td>
                        @else
                        <td colspan="2">
                            <i class="text-danger">Información removida</i>
                        </td>
                        @endif
                        
                        {{ day_production($plan, $dates) }}
                        
                    </tr>
                @endforeach
            </tr>
        @endforeach
        
    </tbody>
</table>
<div>
    <p>
        <span>Finalizado</span>
        <label class="label label-success">&nbsp;</label>
    </p>

    <p>
        <span>Cancelado</span>
        <label class="label label-danger">&nbsp;</label>
    </p>
    <!-- <p>
        <span>Cancelado</span>
        <label class="label label-danger">&nbsp;</label>
    </p> -->
</div>
@stop