app/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('login',  array('as' => 'login.index', 'uses' => 'AuthController@index'));

Route::post('login', array('as' => 'login.signin', 'uses' => 'AuthController@sign_in'));

//Route::group(array('before' => 'auth'), function () {

	Route::get('/', array('as' => 'home.index', 'uses' => 'HomeController@index'));

	Route::get('perfil', array('as' => 'perfil', 'uses' => 'UsersController@perfil'));

	Route::get('logout', array('as' => 'login.logout', 'uses' => 'AuthController@sign_out'));

	Route::resource('users', 'UsersController');

	Route::resource('molds', 'MoldsController');

	Route::resource('lines', 'LinesController');

	Route::resource('efficiency', 'EfficiencyController');

	Route::resource('devices', 'DevicesController');

	Route::resource('production', 'ProductionController');

	Route::get('production/history/{line_id}/{model_id?}/{start_date?}/{end_date?}',
		array(
			'as' => 'production_history',
			'uses' => 'ProductionController@history')
		);

	Route::resource('defects', 'DefectsController');

	Route::resource('models', 'ModelsController');

	Route::resource('plan', 'PlanController');

	Route::get('plan_mold/{mold_id}', 'PlanController@plan_mold');

//});

/*Route::filter('auth', function()
{
    if (Auth::guest()) return Redirect::to('login');
});*/

Route::get('register_production', 'ProductionController@register_production');

$path =  Request::segment(1);

Session::put('nav-option', $path);

//no mismo plan en el mismo horario dependiendo de la linea

//localhost:8000/register_production?line_id=1&arduino_id=1

app/models/Plan.php
<?php
	class Plan extends Eloquent {
		/*public function production(){
			return $this->belongsTo('Production');
		}*/
		public function line() {
			return $this->belongsTo('Line');
		}
		public function user() {
			return $this->belongsTo('User');
		}
		public function model() {
			return $this->belongsTo('Model');
		}
		
		public function shift() {
			return $this->belongsTo('Shift');
		}

		public function type () {
			return $this->belongsTo('PlanType', 'type_id', 'id');
		}

		protected $table = 'plan';
	}
?>

app/models/PlanType.php
<?php
	class PlanType extends Eloquent {

		protected $table = 'plan_type';
	}
?>

app/controllers/PlanController.php
<?php
class PlanController extends BaseController {

   private $autorizado;

   public function __construct(){

      //$path =  Request::segment(1);
   }

   public function index() {
      
      $plans = Plan::orderBy('line_id')->paginate(12);

      return View::make('plan.index', compact('plans'));
   }

   public function create () {

      $types = PlanType::lists('name', 'id');

      $plan = new Plan();

      $lines = Line::lists('name', 'id');

      $molds = Mold::lists('name', 'id');

      return View::make('plan.save', compact('plan', 'lines', 'molds', 'types'));
   }

   public function show ($id) {

      $plan = Plan::find($id);

      return View::make('plan.show', compact('plan'));

   }

   public function plan_mold ($mold_id) {

      $models = Model::where('mold_id', $mold_id)->get();

      return $models;
   }

   public function store () {

      $inputs = Input::all();

      //validar el horario si ya existe un plan con la misma hora o cruza con el horario de otro plan

      //VALIDAR si la hora iniciar es menor que la que finaliza y la fecha iniciar es menor que la que finaliza

      /*if ($inputs['production_date_end'] > $inputs['production_date_begin']) {

         return 'aqui';
         
         return Redirect::back()->withInput();
      }

      if ($inputs['production_time_end'] > $inputs['production_time_begin']) {
            return;
         return Redirect::back()->withInput();
      }*/

      try {

         $plan = new Plan();

         $plan->model_id = $inputs['model_id'];

         $plan->type_id = $inputs['type_id'];

         $plan->line_id = $inputs['line_id'];

         $plan->production_date_begin = $inputs['production_date_begin'];

         $plan->production_date_end = $inputs['production_date_end'];

         $plan->comment = $inputs['comment'];

         $plan->quantity = $inputs['quantity'];

         $plan->status_plan = $inputs['status_plan'];

         $plan->production_time_begin = $inputs['production_time_begin'];

         $plan->production_time_end = $inputs['production_time_end'];

         $plan->save();
         
      } catch (Exception $e) {

         return $e;
         return Redirect::back();
      }

      return Redirect::to('plan')->with('notice', 'El plan ha sido creado correctamente');

   }

   public function edit ($id) {

      $types = PlanType::lists('name', 'id');

      try {

         $plan = Plan::find($id);

         $lines = Line::lists('name', 'id');

         $models = Model::where('id', $plan->model_id)->lists('name', 'id');

         $molds = Mold::lists('name', 'id');
         
      } catch (Exception $e) {

         return Redirect::back();
      }

      return View::make('plan.edit', compact('plan', 'models', 'molds', 'lines', 'types'));
   }

   public function update ($id) {
      
      $inputs = Input::all();

      try {

         $plan = Plan::find($id);

         $plan->model_id = $inputs['model_id'];

         $plan->type_id = $inputs['type_id'];

         $plan->line_id = $inputs['line_id'];

         $plan->production_date_begin = $inputs['production_date_begin'];

         $plan->production_date_end = $inputs['production_date_end'];

         $plan->comment = $inputs['comment'];

         $plan->quantity = $inputs['quantity'];

         if (isset($inputs['status_plan'])) {
            
            $plan->status_plan = $inputs['status_plan'];
         }

         $plan->production_time_begin = $inputs['production_time_begin'];

         $plan->production_time_end = $inputs['production_time_end'];

         $plan->save();
         
      } catch (Exception $e) {

         return Redirect::back();
      }

      return Redirect::to('plan')->with('notice', 'El plan ha sido actualizado correctamente');

   }

   public function destroy ($id) {

      try {

            $plan = Plan::find($id);

            $plan->delete();

      } catch (Exception $e) {
         
         return Redirect::back();
      }
      return Redirect::back()->with('notice', 'Registro eliminado');
   }
}
?>

app/views/plan/_form.blade.php
<div class="row">
  
  <div class="col-md-6">
    <div class="form-group">
      {{ Form::label ('line_id', 'Linea') }}
      {{ Form::select('line_id', array('0'=> '-- Seleccionar --') + $lines, array('selected' => $plan->line_id),  array('id' => 'line_id', 'class' => 'form-control'))}}
    </div>
    <div class="form-group">
      <div> Fecha de 
        {{ Form::label ('production_date_begin', 'inicio') }} y
        {{ Form::label ('production_date_end', 'fin') }} de la producción
      </div>
      <div class="input-daterange input-group" id="">
        {{ Form::text('production_date_begin', null, array('class' => 'form-control datepicker', 'placeholder' => 'yyyy/mm/dd')) }}
        <span class="input-group-addon">a</span>
        {{ Form::text('production_date_end', null, array('class' => 'form-control datepicker', 'placeholder' => 'yyyy/mm/dd')) }}
      </div>
    </div>
  
    <div class="form-group">
      {{ Form::label ('mold_id', 'Molde') }}
      {{ Form::select('mold_id', array('0'=> '-- Seleccionar --') + $molds, array('selected' => ($plan->model) ? $plan->model->mold->id : ''), array('id' => 'select_mold', 'class' => 'form-control'))}}
    </div>

    <div class="form-group">
      {{ Form::label ('model_id', 'Modelo') }}
      @if(is_null($plan->id))
        {{ Form::select('model_id', array('0'=> '-- Seleccionar --'), null, array('id' => 'select_model', 'class' => 'form-control')) }}
      @else
        {{ Form::select('model_id', array('0'=> '-- Seleccionar --') + $models, array('selected' => $plan->model_id), array('id' => 'select_model', 'class' => 'form-control')) }}
      @endif
    </div>

    <div class="form-group">
      {{ Form::label ('type_id', 'Tipo de producción') }}
      {{ Form::select('type_id', $types, array('selected' => $plan->type_id),  array('id' => '', 'class' => 'form-control'))}}
    </div>
    
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <div> Horario de 
        {{ Form::label ('production_time_begin', 'inicio') }} y
        {{ Form::label ('production_time_end', 'fin') }} de la producción
      </div>
      <div class="input-daterange input-group" id="">
        {{ Form::text('production_time_begin', null, array('id'=>'', 'class' => 'form-control datetimepicker', 'placeholder' => '10:50')) }}
        <span class="input-group-addon">a</span>
        {{ Form::text('production_time_end', null, array('id'=>'', 'class' => 'form-control datetimepicker', 'placeholder' => '10:50')) }}      </div>
    </div>
          
    <div class="form-group">
      {{ Form::label ('quantity', 'Cantidad') }}
      {{ Form::text('quantity', null, array('id'=>'quantity', 'class' => 'form-control')) }}
    </div>

    <div class="form-group">
      {{ Form::label ('comment', 'Comentario') }}
      {{ Form::textarea('comment', null, array('id'=>'comment', 'class' => 'form-control', 'rows' => '5')) }}
    </div>
          
    <div class="form-group">
      <label>Activo: </label>
      {{ Form::label('status_plan', 'Si') }}


      {{ Form::radio('status_plan', '1', ($plan->status_plan == '1' or is_null($plan->id)) ? true : false, array('id'=> 'rb_status_plan')) }}

      {{ Form::label('status_plan', 'No')}}
      {{ Form::radio('status_plan', '2', ($plan->status_plan == '2') ? true : false, array('id'=>'rb_status_plan'))}}
    </div>

    <div class="form-group">
  {{ Form::submit('Guardar', array('class' => 'btn btn-success')) }}
  {{ link_to_route('plan.index', 'Cancelar', null, array('class' => 'text-danger')) }}
</div>
  </div>

</div>



 

app/views/plan/edit.blade.php
@extends('layouts.master')
@section('content')
  
  @if(isset($errors))
	   <ul>
	      @foreach($errors as $item)
	         <li> {{ $item }} </li>
	      @endforeach
	   </ul>
	@endif

 	<div class="row">

	<div class="col-md-8 col-md-offset-2">
		<h3>
			Editar
		</h3>
		<hr />
		  {{ Form::model($plan, array('method' => 'PUT' ,'route' => array('plan.update', $plan->id), 'id' => '')) }}
		     @include('plan._form')
		  {{ Form::close() }}
  </div>

  </div>
@stop

app/views/plan/index.blade.php
@extends('layouts.master')
@section('content')

@if(Session::has('notice'))
    <div class="alert alert-success">  {{  Session::get('notice') }} 
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    </div>
@endif
    
    <div class="row">
        <div class="col-md-6">
            <h3>Plan
                {{ link_to_route ('plan.create', 'Nuevo', null, array('class' => 'btn btn-success')) }} 
            </h3>
        </div>
    </div>

    <div>
        <table class="table">
            <thead>
                <tr>
                    <th> Linea </th>
                    <th> Modelo </th>
                    <th> Molde </th>
                    <th> F/H inicio</th>
                    <th> F/H finaliza</th>
                    <th> Cantidad</th>
                    <th> Estatus </th>
                    <th colspan="2">Acciones</th>
                </tr>
            </thead>
            <tbody id="data_plan">
                @foreach($plans as $plan)
                 <tr>
                    <td>
                        @if($plan->line)
                            <a href="{{ route('lines.show', $plan->line->id) }}">
                                {{ str_limit( ($plan->line->name) ? $plan->line->name : 'Sin nombre', 10, '...') }}
                            </a>
                        @else
                            <i class="text-danger">No asignado</i>
                        @endif
                    </td>
                    <td>
                    @if($plan->model)   
                        <a href="{{ route('models.show', $plan->model->id) }}">
                            {{ str_limit($plan->model->name, 10, '...') }}
                        </a>
                    @else
                        <i class="text-danger">No asignado</i>
                    @endif
                    </td>
                    <td>
                    @if($plan->model)
                        @if($plan->model->mold)
                            <a href="{{ route('molds.show', $plan->model->mold->id) }}">
                                {{ str_limit($plan->model->mold->name, 10, '...') }}
                            </a>
                        @endif
                    @else
                        <i class="text-danger">No asignado</i>
                    @endif
                    </td>
                    
                    <td> {{ $plan->production_date_begin }} <br /> {{ $plan->production_time_begin }} </td>

                    <td> {{ $plan->production_date_end  }} <br /> {{ $plan->production_time_end }} </td>
                    
                    <td> {{ $plan->quantity }} </td>

                    <td>
                        <span  class="label label-{{ ($plan->status_plan == 1) ? 'success' : 'danger' }}" >
                        @if($plan->status_plan == 1)
                            Activo
                        @elseif($plan->status_plan == 2)
                            Inactivo
                        @else
                            <i class="text-danger">Erroneo</i>
                        @endif
                        </span>
                    </td>

                    <td> 
                        {{ link_to_route('plan.edit', 'Editar', $plan->id, array('class' => 'btn btn-primary')) }}
                    </td>

                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('plan.destroy', $plan->id))) }}
                            {{ Form::submit('Eliminiar', array('class' => 'btn btn-danger destroy-register'))}}
                        {{ Form::close() }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @if($plans->count())
         {{ $plans->links() }}
    @else
        <p class="text-danger">No se encontro registros</p>
    @endif
@stop

app/views/plan/save.blade.php
@extends('layouts.master')
@section('content')
  @if(isset($errors))
	   <ul>
	      @foreach($errors as $item)
	         <li> {{ $item }} </li>
	      @endforeach
	   </ul>
	@endif
<div class="row">

	<div class="col-md-8 col-md-offset-2">
		<h3>
			Nuevo 
		</h3>
		<hr />
		<div>
	  	{{ Form::model($plan, array('route' => 'plan.store')) }}
	    	@include('plan._form')
	  	{{ Form::close() }}
	 	</div>
	</div>
</div>
@stop

app/views/plan/show.blade.php
@extends('layouts.master')
@section('content')
  
  @if(isset($errors))
	   <ul>
	      @foreach($errors as $item)
	         <li> {{ $item }} </li>
	      @endforeach
	   </ul>
	@endif

 	<div class="row">

	<div class="col-md-8 col-md-offset-2">
		<h3>
			Plan 
		</h3>

		<hr />

		@if($plan)
			<p>
				<label>
					Identificador:
				</label>
				{{ $plan->id }}
			</p>
			<p>
				<label>
					Molde:
				</label>
				{{ $plan->model->mold->name }}
			</p>
			<p>
				<label>
					Modelo:
				</label>
				{{ $plan->model->name }}
			</p>
			<p>
				<label>
					Fecha de inicio:
				</label>
				{{ date('d F Y', strtotime($plan->production_date_begin)) }}
			</p>
			<p>
				<label>
					Fecha termino:
				</label>
				{{ date('d F Y', strtotime($plan->production_date_end)) }}
			</p>
			<p>
				<label>
					Hora de inicio:
				</label>
				{{ $plan->production_time_begin }}
			</p>
			<p>
				<label>
					Hora termino:
				</label>
				{{ $plan->production_time_end }}
			</p>
			<p>
				<label>
					Cantidad:
				</label>
				<b>{{ $plan->quantity }}</b>
			</p>

			
			<p>
			<label>
					Estatus
				</label>
			 	<span  class="label label-{{ ($plan->status_plan == 1) ? 'success' : 'danger' }}" >
                    @if($plan->status_plan == 1)
                        Activo
                    @elseif($plan->status_plan == 2)
                        Inactivo
                    @else
                        <i class="text-danger">Erroneo</i>
                    @endif
                </span>
			</p>

			<p>
				<label>
					Tipo de plan:
				</label>
				{{ $plan->type->name }}
			</p>

			<p>
				<label>
					Linea:
				</label>
				{{ $plan->line->name }}
			</p>

			<p>
				<label>
					Creado
				</label>
				{{ $plan->created_at }}
			</p>
			<p>
				<label>
					Comentarios:
				</label>
				{{ $plan->comment }}
			</p>
		@endif
		{{ link_to_route('plan.edit', 'Editar', $plan->id, array('class' => 'btn btn-primary')) }}
		<a class="text-warning">Regresar</a>
		
  	</div>

  </div>
@stop